dist: bionic
language: cpp
cache: ccache
git:
  depth: false
matrix:
  fast_finish: true
  include:

    - name: "Astyle"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - astyle
      script:
        - ./astyle.sh

    - name: "GCC 4.8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libnuma-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
      install:
      script:
        - ./build.sh

    - name: "GCC 9.0"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libnuma-dev
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      install:
      script:
        - ./build.sh

    - name: "Clang 10"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - libnuma-dev
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
      install:
      script:
        - ./build.sh

before_install:
  - eval "${MATRIX_EVAL}"
